import { randomBytes } from 'node:crypto';
import { isIPv6 } from 'node:net';
import { ConfigError,type ConfigIssue } from './errors.ts';
import { Secret } from './secret.ts';
export const ENV_VAR_NAMES=['NODE_ENV','HOST','PORT','LOG_LEVEL','DATABASE_URL','JWT_SECRET','JWT_ISSUER','JWT_AUDIENCE'] as const;
export type EnvVarName=(typeof ENV_VAR_NAMES)[number]; export type EnvSource=Readonly<Record<string,string|undefined>>;
const NODE_ENVS=['development','test','production'] as const;const LOG_LEVELS=['debug','info','warn','error','silent'] as const;
export type NodeEnv=(typeof NODE_ENVS)[number];export type LogLevel=(typeof LOG_LEVELS)[number];
export interface AppConfig{readonly env:NodeEnv;readonly server:{readonly host:string;readonly port:number};readonly logLevel:LogLevel;readonly database:{readonly url:Secret<string>};readonly auth:{readonly jwtSecret:Secret<string>;readonly jwtIssuer:string;readonly jwtAudience:string;}}
const DEFAULTS={env:'development',host:'127.0.0.1',port:3000,logLevel:'info'} as const satisfies {env:NodeEnv;host:string;port:number;logLevel:LogLevel};
function read(env:EnvSource,name:EnvVarName):string|undefined{if(!Object.hasOwn(env,name))return undefined;const raw=env[name]?.trim();return raw===undefined||raw===''?undefined:raw;}
function readChoice<T extends string>(env:EnvSource,name:EnvVarName,allowed:readonly T[],fallback:T,issues:ConfigIssue[]):T{const raw=read(env,name);if(raw===undefined)return fallback;const match=allowed.find(c=>c===raw);if(match===undefined){issues.push({variable:name,message:`must be one of: ${allowed.join(', ')} (received "${raw}")`});return fallback;}return match;}
function readPort(env:EnvSource,name:EnvVarName,fallback:number,issues:ConfigIssue[]):number{const raw=read(env,name);if(raw===undefined)return fallback;const port=/^\d+$/.test(raw)?Number(raw):Number.NaN;if(!Number.isInteger(port)||port<1||port>65535){issues.push({variable:name,message:`must be an integer between 1 and 65535 (received "${raw}")`});return fallback;}return port;}
function readHost(env:EnvSource,name:EnvVarName,fallback:string,issues:ConfigIssue[]):string{const raw=read(env,name);if(raw===undefined)return fallback;if(!isIPv6(raw)&&!/^[A-Za-z0-9._-]+$/.test(raw)){issues.push({variable:name,message:`must be a bare host name or IP address, without scheme, port or path (received "${raw}")`});return fallback;}return raw;}
function readSecret(env:EnvSource,name:EnvVarName,issues:ConfigIssue,minimumLength:number):Secret<string>|undefined{const raw=read(env,name);if(raw===undefined){issues.push({variable:name,message:'is required'});return undefined;}if(raw.length<minimumLength){issues.push({variable:name,message:`must contain at least ${minimumLength} characters (value hidden because it is a secret)`});return undefined;}return new Secret(raw);}
function readPostgresUrl(env:EnvSource,name:EnvVarName,issues:ConfigIssue[]):Secret<string>|undefined{const raw=read(env,name);if(raw===undefined){issues.push({variable:name,message:'is required'});return undefined;}const invalid=(reason:string):undefined=>{issues.push({variable:name,message:`${reason} (value hidden because it is a secret)`});return undefined;};let url:URL;try{url=new URL(raw);}catch{return invalid('must be a valid PostgreSQL URL: postgres://user:password@host:port/database');}if(url.protocol!=='postgres:'&&url.protocol!=='postgresql:')return invalid('must use the postgres:// or postgresql:// scheme');if(url.hostname==='')return invalid('must include a host');if(url.pathname.length<=1)return invalid('must include a database name');return new Secret(raw);}
export function loadConfig(env:EnvSource):AppConfig{const issues:ConfigIssue[]=[];const nodeEnv=readChoice(env,'NODE_ENV',NODE_ENVS,DEFAULTS.env,issues);const host=readHost(env,'HOST',DEFAULTS.host,issues);const port=readPort(env,'PORT',DEFAULTS.port,issues);const logLevel=readChoice(env,'LOG_LEVEL',LOG_LEVELS,DEFAULTS.logLevel,issues);const databaseUrl=readPostgresUrl(env,'DATABASE_URL',issues);const rawJwtSecret=read(env,'JWT_SECRET');let jwtSecret:Secret<string>|undefined;if(rawJwtSecret===undefined&&nodeEnv!=='production')jwtSecret=new Secret(randomBytes(32).toString('base64url'));else jwtSecret=readSecret(env,'JWT_SECRET',issues,32);const jwtIssuer=read(env,'JWT_ISSUER')??'rebuplica-27';const jwtAudience=read(env,'JWT_AUDIENCE')??'rebuplica-api';if(issues.length>0||databaseUrl===undefined||jwtSecret===undefined)throw new ConfigError(issues);return Object.freeze({env:nodeEnv,server:Object.freeze({host,port}),logLevel,database:Object.freeze({url:databaseUrl}),auth:Object.freeze({jwtSecret,jwtIssuer,jwtAudience})});}
