import { randomUUID } from 'node:crypto';
import type { IncomingMessage,ServerResponse } from 'node:http';
import { payloadTooLarge,unsupportedMediaType,validationError } from './errors.ts';

export const DEFAULT_MAXIMUM_BODY_BYTES = 64 * 1024;
const REQUEST_ID_PATTERN = /^[A-Za-z0-9._-]{1,64}$/u;
const JSON_CONTENT_TYPE_PATTERN = /^application\/(?:[\w.+-]+\+)?json(?:\s*;.*)?$/iu;

export interface ResponseHeaders {
  readonly [name: string]: string;
}

export const json = (response: ServerResponse,status: number,body: unknown,headers: ResponseHeaders = {}): void => {
  const payload = JSON.stringify(body);
  response.statusCode = status;
  response.setHeader('content-type','application/json; charset=utf-8');
  response.setHeader('content-length',Buffer.byteLength(payload));
  response.setHeader('cache-control','no-store');
  for (const [name,value] of Object.entries(headers)) response.setHeader(name,value);
  response.end(payload);
};

/**
 * Headers applied to every response. They are deliberately conservative for a JSON
 * API and never include a wildcard CORS origin (see `applyCors`).
 */
export const applySecurityHeaders = (response: ServerResponse): void => {
  response.setHeader('x-content-type-options','nosniff');
  response.setHeader('x-frame-options','DENY');
  response.setHeader('referrer-policy','no-referrer');
  response.setHeader('content-security-policy',"default-src 'none'; frame-ancestors 'none'; base-uri 'none'");
  response.setHeader('cross-origin-opener-policy','same-origin');
  response.removeHeader('x-powered-by');
};

export interface CorsDecision {
  readonly allowed: boolean;
  readonly headers: ResponseHeaders;
}

/**
 * Cross origin policy: only explicitly configured origins are echoed back, the
 * response always varies on `Origin`, and credentials are not used (the API is
 * token based), so no cookie rules are involved.
 */
export const resolveCors = (origin: string | undefined,allowedOrigins: readonly string[]): CorsDecision => {
  if (origin === undefined || origin === '') return {allowed:false,headers:{}};
  if (!allowedOrigins.includes(origin)) return {allowed:false,headers:{vary:'Origin'}};
  return {
    allowed:true,
    headers:{
      vary:'Origin',
      'access-control-allow-origin':origin,
      'access-control-allow-methods':'GET, POST, OPTIONS',
      'access-control-allow-headers':'authorization, content-type, x-request-id',
      'access-control-max-age':'600',
    },
  };
};

/** Request id: generated by the server, or reused only when the client value is safe. */
export const resolveRequestId = (request: IncomingMessage): string => {
  const header = request.headers['x-request-id'];
  const candidate = Array.isArray(header) ? header[0] : header;
  if (candidate !== undefined && REQUEST_ID_PATTERN.test(candidate)) return candidate;
  return randomUUID();
};

const isValidIpv4 = (value: string): boolean => {
  const parts = value.split('.');
  if (parts.length !== 4) return false;
  return parts.every(part => /^\d{1,3}$/u.test(part) && Number(part) <= 255);
};

const isValidIpv6 = (value: string): boolean => /^[0-9a-f:]+$/iu.test(value) && value.includes(':');

const isValidIp = (value: string): boolean => isValidIpv4(value) || (isValidIpv6(value) && value.length <= 45);

/**
 * Client address used for rate limiting.
 *
 * `X-Forwarded-For` is only consulted when `trustedProxyHops` is greater than zero,
 * because a client can otherwise spoof the header and escape its rate limit bucket.
 * With N trusted hops the entry N positions from the right (the address added by the
 * outermost trusted proxy) is used; malformed values fall back to the socket address.
 */
export const resolveClientAddress = (request: IncomingMessage,trustedProxyHops: number): string => {
  const socketAddress = request.socket.remoteAddress ?? 'unknown';
  if (trustedProxyHops < 1) return socketAddress;
  const header = request.headers['x-forwarded-for'];
  const raw = Array.isArray(header) ? header[0] : header;
  if (raw === undefined) return socketAddress;
  const chain = raw.split(',').map(entry => entry.trim()).filter(entry => entry !== '');
  const index = chain.length - trustedProxyHops;
  const candidate = index >= 0 && index < chain.length ? chain[index] : undefined;
  if (candidate === undefined || !isValidIp(candidate)) return socketAddress;
  return candidate;
};

export interface ParseJsonOptions {
  readonly maxBytes?: number | undefined;
}

/** Reads and parses a JSON object body, enforcing size and content type limits. */
export const parseJson = async (request: IncomingMessage,options: ParseJsonOptions = {}): Promise<Record<string,unknown>> => {
  const maxBytes = options.maxBytes ?? DEFAULT_MAXIMUM_BODY_BYTES;
  const contentType = request.headers['content-type'];
  if (contentType !== undefined && !JSON_CONTENT_TYPE_PATTERN.test(Array.isArray(contentType) ? contentType[0] ?? '' : contentType)) {
    throw unsupportedMediaType();
  }
  const chunks: Buffer[] = [];
  let size = 0;
  let overflowed = false;
  // Above the hard cap the socket is destroyed instead of draining an unbounded upload.
  const hardLimit = Math.max(4 * 1024 * 1024,maxBytes * 8);
  for await (const chunk of request) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk as string);
    size += buffer.length;
    if (size > hardLimit) {
      request.destroy();
      throw payloadTooLarge();
    }
    if (size > maxBytes) {
      // Stop buffering but keep draining, otherwise the 413 cannot reach the client.
      overflowed = true;
      chunks.length = 0;
      continue;
    }
    chunks.push(buffer);
  }
  if (overflowed) throw payloadTooLarge();
  if (size === 0) return {};
  let parsed: unknown;
  try {
    parsed = JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;
  } catch {
    throw validationError('Request body must be valid JSON');
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) throw validationError('Request body must be a JSON object');
  return parsed as Record<string, unknown>;
};

/** Reads the `Authorization: Bearer <token>` header. */
export const readBearerToken = (request: IncomingMessage): string | null => {
  const header = request.headers.authorization;
  if (header === undefined) return null;
  const [scheme,value] = header.split(' ');
  if (scheme === undefined || value === undefined) return null;
  if (scheme.toLowerCase() !== 'bearer' || value.trim() === '') return null;
  return value.trim();
};
