import { randomUUID } from 'node:crypto';
import { DeterministicRng } from './rng.ts';
import { defaultDecisionRegistry,type DecisionRegistry } from './decisions.ts';
import type { DomainEvent } from './events.ts';
import type { DecisionInput,DecisionRecord,GameId,GameState,UserId } from './types.ts';
export interface GameAggregate{readonly state:GameState;readonly version:number;readonly events:readonly DomainEvent[];}
export const createGame=(ownerId:UserId,gameId:GameId=randomUUID(),seed=1,startDate='2027-01-01T00:00:00.000Z'):GameAggregate=>{const state:GameState={gameId,ownerId,seed:seed>>>0,turn:0,world:{date:startDate,economy:{},society:{},institutions:{},flags:{}}};const event:DomainEvent={type:'GameCreated',eventId:randomUUID(),version:1,state};return{state,version:1,events:[event]};};
export const applyDecision=(aggregate:GameAggregate,actorId:UserId,input:DecisionInput,registry:DecisionRegistry=defaultDecisionRegistry()):GameAggregate=>{if(actorId!==aggregate.state.ownerId)throw new Error('Actor is not authorized for this game');const decision:DecisionRecord={...input,decisionId:randomUUID(),turn:aggregate.state.turn,actorId};const next=registry.apply(aggregate.state,input,{rng:new DeterministicRng(aggregate.state.seed^aggregate.version),date:aggregate.state.world.date});const version=aggregate.version+1;const event:DomainEvent={type:'DecisionApplied',eventId:randomUUID(),version,decision,state:next};return{state:next,version,events:[...aggregate.events,event]};};
export const advanceTurn=(aggregate:GameAggregate,days=30):GameAggregate=>{if(!Number.isInteger(days)||days<1)throw new Error('Turn duration must be a positive integer');const current=new Date(aggregate.state.world.date);if(Number.isNaN(current.getTime()))throw new Error('Game contains invalid world date');const nextDate=new Date(current.getTime()+days*86400000).toISOString();const next:GameState={...aggregate.state,turn:aggregate.state.turn+1,world:{...aggregate.state.world,date:nextDate}};const version=aggregate.version+1;const event:DomainEvent={type:'TurnAdvanced',eventId:randomUUID(),version,turn:next.turn,state:next};return{state:next,version,events:[...aggregate.events,event]};};
